export const SITE = {
  brand: "Night Series",
  tagline: "Private BMW 750 chauffeur — Baltimore, BWI, DCA, IAD, and Washington.",
  phoneDisplay: "667 · 207 · 1472",
  phoneTel: "+16672071472",
  driver: "Ryan J.",
  vehicle: "BMW 750",
  exterior: "Pearl white",
  interior: "Red leather",
  city: "Baltimore, MD",
  coverage: ["Baltimore metro", "Annapolis", "Columbia", "BWI · DCA · IAD", "Washington, D.C."],
  flyer: {
    luxuryWord: "LUXURY",
    serviceLine: "CHAUFFEUR SERVICE",
    tagA: "Arrive in style. Every time.",
    tagB: "White BMW 750 · Power. Prestige. Performance.",
    pillars: [
      { title: "Professional chauffeurs", icon: "shield" as const },
      { title: "On time, every time", icon: "clock" as const },
      { title: "Private and discreet", icon: "lock" as const },
      { title: "Luxury you can feel", icon: "star" as const },
    ],
    occasions: [
      { label: "Weddings", icon: "heart" as const },
      { label: "Proms and formal events", icon: "grad" as const },
      { label: "Airport transfers", icon: "plane" as const },
      { label: "Business travel", icon: "case" as const },
      { label: "Special occasions", icon: "spark" as const },
      { label: "Photo shoots", icon: "cam" as const },
      { label: "Night outs and more", icon: "moon" as const },
    ],
    luxuryTitle: "The luxury experience",
    luxuryBullets: [
      "Red leather interior",
      "Ambient cabin lighting",
      "Heated, ventilated and massaging seats",
      "Smooth, quiet, powerful ride",
      "Complimentary water and phone chargers",
      "Personalized music and cabin mood",
      "Clean, private, chauffeur-grade space",
    ],
    interiors: [
      { src: "/night/cabin-rear.png", alt: "Rear cabin — red leather seating" },
      { src: "/night/cabin-dash.png", alt: "Cockpit — BMW dash and ambient light" },
      { src: "/night/cabin-rear.png", alt: "Cabin detail — quilting and trim", objectPosition: "78% 42%" },
    ],
    driverLine: "Driven by professionalism.",
    driverQuote: "Your comfort. Your time. My priority.",
    footerStrip: "Reliable · Respectful · Professional",
  },
  hero: {
    kicker: "Serving Baltimore and surrounding areas",
    sub: "Private hire in a white BMW 750 — one vehicle, one chauffeur, on your schedule.",
  },
  reserve: {
    occasions: ["Night out", "Wedding", "Anniversary", "Airport", "Business", "Prom", "Photo shoot", "Other"],
    tabs: [
      { id: "one-way" as const, label: "One way" },
      { id: "by-hour" as const, label: "By the hour" },
      { id: "event" as const, label: "Full evening" },
    ],
  },
};
